name: Deploy Terraform Code

on:
  workflow_dispatch:
    inputs:
      environment:
        type: env

jobs:
  lint-validate-terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version: [0.12.x, 0.13.x, 0.14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}

      - name: Lint Terraform code formatting
        run: |
          terraform fmt -check

      - name: Validate Terraform code
        run: terraform validate

  plan-infrastructure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version: [0.12.x, 0.13.x, 0.14.x]
    needs: lint-validate-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}

      - name: Initialize Terraform
        run: terraform init --var-file=${{ env.ENVIRONMENT }}.tfvars

      - name: Plan Terraform changes
        run: terraform plan

  manual-deploy-confirmation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version: [0.12.x, 0.13.x, 0.14.x]
    needs: plan-infrastructure
    if: github.event_name == 'workflow_run' && github.event.inputs.environment == 'prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}

      - name: Check for manual confirmation
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Deployment to environment ${{ github.event.inputs.environment }} is planned.")
            console.log("Please review the plan and confirm deployment manually.")
            console.log("To confirm deployment, comment 'deploy' on this workflow run.")

  deploy-infrastructure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version: [0.12.x, 0.13.x, 0.14.x]
    needs: manual-deploy-confirmation
    if: github.ref == 'refs/heads/main' && startsWith(github.event.comment.body, 'deploy')
    env:
      TF_VAR_GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
      TF_VAR_GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}

      - name: Initialize Terraform
        run: terraform init --var-file=${{ env.ENVIRONMENT }}.tfvars

      - name: Apply Terraform changes
        run: terraform apply -auto-approve --var-file=${{ env.ENVIRONMENT }}.tfvars
